# ROM Manager - Retro game collection management
# Tengil package using Docker Compose integration

name: ROM Manager
description: Retro game collection manager (romM) with web interface
category: Gaming
tags: [gaming, retro, roms, emulation, collection-manager, romm]

components:
  - romM web interface (manage ROMs, artwork, metadata)
  - Organized ROM storage by system
  - Samba shares for easy ROM uploads
  - MariaDB database for metadata
  - Redis cache for background tasks

requirements:
  min_ram_mb: 2048
  min_disk_gb: 50
  recommended_ram_mb: 4096
  recommended_cores: 2

# DOCKER COMPOSE SOURCE (maintained by romM developers)
docker_compose:
  # Local cache for testing
  cache: "../../.local/romm-docker-compose.example.yml"
  # Source: Official romM compose file (fallback if cache missing)
  source: "https://raw.githubusercontent.com/rommapp/romm/master/docker-compose.example.yml"
  
  # Which volumes we care about (others are Docker volumes)
  managed_volumes:
    - /path/to/library  # Will be mapped to /roms
    - /path/to/assets   # Will be mapped to /assets
    - /path/to/config   # Will be mapped to /config

# TENGIL'S VALUE-ADD: Storage optimization hints
storage_hints:
  "/path/to/library":
    profile: media  # 1M recordsize, lz4 compression, atime=off
    size_estimate: "500GB"
    why: "ROM files range from KB (NES) to GB (Switch). 1M recordsize optimal for large files. LZ4 compression good for pre-compressed data (ZIPs)."
    mount_as: /roms  # Actual mount point in tengil.yml
  
  "/path/to/assets":
    profile: media  # Good for save states, screenshots
    size_estimate: "50GB"
    why: "Save states, screenshots, uploaded artwork. Media profile optimal for image files."
    mount_as: /assets
  
  "/path/to/config":
    profile: dev  # 128K recordsize for config files
    size_estimate: "1GB"
    why: "romM configuration YAML files. Small text files benefit from smaller recordsize."
    mount_as: /config

# TENGIL'S VALUE-ADD: Network share recommendations
share_recommendations:
  "/path/to/library":
    smb: true
    smb_name: "ROMs"
    read_only: false
    browseable: yes
    comment: "Retro game ROM library - add your games here!"
    why: "Users need easy access to upload ROMs from Windows/Mac/Steam Deck. SMB provides Windows-native file sharing."

# TENGIL'S VALUE-ADD: Container resource sizing
container:
  memory: 2048
  cores: 2
  disk_size: 10
  template: debian-12-standard
  post_install:
    - tteck/docker
    - tteck/portainer
  why: "2GB RAM sufficient for most collections. Portainer provides easy Docker Compose deployment UI."

# RUNTIME CONFIGURATION
deployment:
  runtime: docker
  method: lxc  # Options: lxc (lightweight, fast) or vm (full isolation, better compatibility)
  why: |
    LXC Docker host is the default - lightweight, integrates with Proxmox storage, fast startup.
    Use VM if you need full isolation, GPU passthrough, or encounter LXC compatibility issues.
    
    Both modes work identically from user perspective - Tengil handles the differences.
    
    To use VM instead: tg init --package rom-manager-compose --runtime docker-vm

customize:
  - key: pool_name
    prompt: "ZFS pool name"
    default: tank
    type: string
    help: "Pool for ROM storage (needs 50GB+ free for large collections)"

  - key: romm_memory
    prompt: "RAM for romM container (MB)"
    default: 2048
    type: int
    min: 1024
    max: 8192
    help: "2GB sufficient for most collections, 4GB+ for very large libraries (10K+ games)"

related:
  - gaming-station  # Add game servers and streaming
  - nas-basic  # Add more storage for ROM backups

notes: |
  Your ROM manager is ready! Organize your retro game collection.

  Access points:
  - romM Web UI: http://proxmox:8080
  - Portainer: http://proxmox:9000 (manage Docker)
  - ROM share: \\proxmox\ROMs

  Setting up romM (one-time, 2 minutes):
  1. Access Portainer: http://proxmox:9000
  2. Go to: Stacks > Add Stack
  3. Name: romm
  4. Paste the docker-compose.yml (generated by Tengil)
  5. Fill in secrets:
     - DB_PASSWD: (auto-generated by Tengil)
     - ROMM_AUTH_SECRET_KEY: (auto-generated by Tengil)
     - MARIADB_ROOT_PASSWORD: (auto-generated by Tengil)
     - MARIADB_PASSWORD: (same as DB_PASSWD)
  6. Click "Deploy the stack"
  7. Wait 1-2 minutes for romM to start
  8. Access romM: http://proxmox:8080

  Tengil will show you the generated docker-compose.yml with:
  - Correct volume paths (/roms, /assets, /config)
  - Generated secrets (secure random keys)
  - Optimized for your Proxmox setup

  First-time romM setup:
  1. Open http://proxmox:8080
  2. Create admin account
  3. Configure metadata sources:
     - IGDB (built-in)
     - SteamGridDB (add API key for better artwork)
     - ScreenScraper (optional, requires account)
     - RetroAchievements (optional, for achievements)
  4. Add platforms (NES, SNES, PS1, etc.)
  5. Upload ROMs via web UI or Samba share

  Adding ROMs:
  Method 1 - Samba share (easiest):
  - Windows: \\proxmox\ROMs
  - Mac: smb://proxmox/ROMs (cmd+K in Finder)
  - Create folders: NES/, SNES/, PS1/, etc.
  - Copy ROM files
  - romM auto-detects and fetches metadata

  Method 2 - Web upload:
  - romM UI > Library > Upload
  - Select platform
  - Upload ROM files
  - Metadata fetched automatically

  Organizing your collection:
  - Create platform folders: NES/, SNES/, N64/, PS1/, etc.
  - romM supports 100+ platforms
  - Artwork downloaded automatically
  - Box art, screenshots, logos all managed

  Supported systems (examples):
  - Nintendo: NES, SNES, N64, GameCube, Wii, Switch
  - Sony: PS1, PS2, PS3, PSP, PS Vita
  - Sega: Genesis, Saturn, Dreamcast, Game Gear
  - Arcade: MAME, FinalBurn Neo
  - Handhelds: Game Boy, GBA, DS, 3DS
  - And 80+ more platforms!

  Advanced features:
  - Multi-file ROM support (CD images with .cue/.bin)
  - Region detection and filtering
  - Save state management
  - Play time tracking
  - Favorites and collections
  - Mobile-friendly responsive UI

  Integrations:
  - EmulationStation: Point to /roms for game library
  - RetroArch: Use romM as ROM source
  - Kodi: Add romM as game library
  - LaunchBox: Sync with romM metadata

  SteamGridDB API (optional but recommended):
  1. Create account: https://www.steamgriddb.com/
  2. Generate API key: Profile > Preferences > API
  3. Add to docker-compose.yml: STEAMGRIDDB_API_KEY=your-key
  4. Better artwork quality!

  Performance tips:
  - ROMs on HDD pool is fine (large sequential files)
  - Use SSD if you have 10K+ ROMs for faster scanning
  - 2GB RAM handles most collections
  - 4GB+ RAM for libraries over 5K games
  - Tengil already disabled atime for performance!

  Backup strategy:
  - ROMs: Copy to external drive (irreplaceable!)
  - Database: Automatic in mysql_data Docker volume
  - Metadata: Re-downloadable from sources
  - Snapshots: Use ZFS snapshots via Tengil

  Common ROM organization:
  ```
  \\proxmox\ROMs\
    NES/
      Super Mario Bros.zip
      The Legend of Zelda.zip
    SNES/
      Super Mario World.zip
      Final Fantasy VI.zip
    PS1/
      Final Fantasy VII/
        FF7 (Disc 1).cue
        FF7 (Disc 1).bin
  ```

  Troubleshooting:
  - romM not starting: Check Portainer logs
  - No artwork: Add SteamGridDB API key
  - ROMs not detected: Check folder structure and permissions
  - Slow scanning: Move to SSD or reduce collection size

  Next steps:
  - Set up EmulationStation (gaming-station package)
  - Add RetroArch for playing games
  - Configure remote access (remote-access package)
  - Set up automated backups
  - Explore romM integrations (Kodi, LaunchBox)
